-- Root module for the Precedence library.
--
-- `Basic` is the hand-written model of `src/lib.rs::Ladder::resolve` and its
-- theorems. `Vectors` is GENERATED by `just gen-vectors` from the Rust truth
-- table and must never be hand-edited — CI regenerates it and fails on a diff.
import Precedence.Basic
import Precedence.Vectors
